import tailwindcssAnimate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#93c5fd",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#f8fafc",
        "error": "#ba1a1a",
        "primary": "#3b82f6",
        "on-secondary-fixed-variant": "#94a3b8",
        "surface-variant": "#1e293b",
        "surface": "#0b0f19",
        "on-surface": "#f8fafc",
        "tertiary-fixed": "#e4e2e1",
        "secondary": "#94a3b8",
        "on-tertiary-fixed": "#1b1c1c",
        "background": "#020617",
        "on-primary-fixed": "#1e3a8a",
        "surface-dim": "#1e293b",
        "on-primary-container": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-tint": "#3b82f6",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#93c5fd",
        "surface-container-highest": "#334155",
        "secondary-fixed": "#dbeafe",
        "outline": "#475569",
        "surface-bright": "#0b0f19",
        "tertiary": "#94a3b8",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container-high": "#1e293b",
        "surface-container": "#0f172a",
        "primary-fixed": "#dbeafe",
        "on-background": "#f8fafc",
        "primary-container": "#1e40af",
        "on-primary-fixed-variant": "#1e3a8a",
        "inverse-on-surface": "#1e293b",
        "on-tertiary-container": "#ffffff",
        "inverse-surface": "#f8fafc",
        "on-secondary": "#0f172a",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#020617",
        "on-tertiary-fixed-variant": "#474746",
        "on-secondary-container": "#94a3b8",
        "inverse-primary": "#93c5fd",
        "on-surface-variant": "#cbd5e1",
        "tertiary-container": "#757474",
        "secondary-container": "#1e40af",
        "outline-variant": "#1e293b"
      },

      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Sora"],
        label: ["Sora"],
        inter: ["Inter"],
        space: ["Space Grotesk"],
        sora: ["Sora"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
