import tailwindcssAnimate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#93c5fd",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#0f172a",
        "error": "#ba1a1a",
        "primary": "#3b82f6",
        "on-secondary-fixed-variant": "#475569",
        "surface-variant": "#f1f5f9",
        "surface": "#ffffff",
        "on-surface": "#0f172a",
        "tertiary-fixed": "#e2e8f0",
        "secondary": "#475569",
        "on-tertiary-fixed": "#0f172a",
        "background": "#ffffff",
        "on-primary-fixed": "#1e3a8a",
        "surface-dim": "#f1f5f9",
        "on-primary-container": "#1e3a8a",
        "tertiary-fixed-dim": "#cbd5e1",
        "surface-tint": "#3b82f6",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#cbd5e1",
        "surface-container-highest": "#e2e8f0",
        "secondary-fixed": "#e2e8f0",
        "outline": "#475569",
        "surface-bright": "#ffffff",
        "tertiary": "#475569",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container-high": "#f1f5f9",
        "surface-container": "#f8fafc",
        "primary-fixed": "#dbeafe",
        "on-background": "#0f172a",
        "primary-container": "#dbeafe",
        "on-primary-fixed-variant": "#1e3a8a",
        "inverse-on-surface": "#f8fafc",
        "on-tertiary-container": "#1e3a8a",
        "inverse-surface": "#0f172a",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ffffff",
        "on-tertiary-fixed-variant": "#475569",
        "on-secondary-container": "#0f172a",
        "inverse-primary": "#93c5fd",
        "on-surface-variant": "#334155",
        "tertiary-container": "#cbd5e1",
        "secondary-container": "#e2e8f0",
        "outline-variant": "#e2e8f0"
      },

      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Sora"],
        label: ["Sora"],
        inter: ["Inter"],
        space: ["Space Grotesk"],
        sora: ["Sora"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
