/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffb3af",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#1c1831",
        "error": "#ba1a1a",
        "primary": "#a92f32",
        "on-secondary-fixed-variant": "#48435e",
        "surface-variant": "#e5e2e1",
        "surface": "#fcf9f8",
        "on-surface": "#1b1b1b",
        "tertiary-fixed": "#e4e2e1",
        "secondary": "#605b77",
        "on-tertiary-fixed": "#1b1c1c",
        "background": "#fcf9f8",
        "on-primary-fixed": "#410005",
        "surface-dim": "#dcd9d9",
        "on-primary-container": "#fffbff",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-tint": "#ac3134",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#cac2e3",
        "surface-container-highest": "#e5e2e1",
        "secondary-fixed": "#e6deff",
        "outline": "#8c716f",
        "surface-bright": "#fcf9f8",
        "tertiary": "#5c5c5c",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container-high": "#eae7e7",
        "surface-container": "#f0eded",
        "primary-fixed": "#ffdad7",
        "on-background": "#1b1b1b",
        "primary-container": "#ca4748",
        "on-primary-fixed-variant": "#8b1820",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary-container": "#fffcfb",
        "inverse-surface": "#313030",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed-variant": "#474746",
        "on-secondary-container": "#645f7b",
        "inverse-primary": "#ffb3af",
        "on-surface-variant": "#584140",
        "tertiary-container": "#757474",
        "secondary-container": "#e3dbfd",
        "outline-variant": "#dfbfbd"
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Sora"],
        label: ["Sora"],
        inter: ["Inter"],
        space: ["Space Grotesk"],
        sora: ["Sora"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
